### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by kylewsbm** [areed1192/td-ameritrade-python-api#105]
The very first time I ran the streaming API sample you provided, it worked.  However, everytime I try to run the sample since then, it throws this error:

```console
Traceback (most recent call last):

  File "G:\My Drive\Python\Trading\Websockettemp.py", line 130, in <module>
    TDStreamingClient.stream()

  File "C:\ProgramData\Anaconda3\lib\site-packages\td\stream.py", line 534, in stream
    self.loop.run_until_complete(self._connect())

  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 592, in run_until_complete
    self._check_running()

  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running
```

This persists even after shutting down the editor, the console, turning off and on the computer.  I am unable to figure out why.  Any ideas?

Thanks so much for your help!

**Comment by areed1192** [comment]
Quick question are you running this inside of a **Jupyter Notebook**?

**Comment by kylewsbm** [comment]
> Quick question are you running this inside of a **Jupyter Notebook**?

Nope, in Spyder inside of Anaconda
