### ISSUE TITLE
json decode error in test_streaming_client.py

### ISSUE THREAD

**Issue by littleyoda83** [areed1192/td-ameritrade-python-api#137]
I'm getting the traceback error below when using the test_streaming_client.py

```
Traceback (most recent call last):
  File "test_streaming_client.py", line 8, in <module>
    fields_dict=json.load(fp=fields_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 3 (char 4)
```

**Comment by hhashim1** [comment]
I have the same problem. Was there any solution for this?
