### ISSUE TITLE
UNSAFE_LEGACY_RENEGOTIATION_DISABLED on Mac OSX

### ISSUE THREAD

**Issue by nittanycolonial** [areed1192/td-ameritrade-python-api#236]
I am running this library on Max OSX Big Sur 11.6 and I keep on running in the SSL/urlib3 error of UNSAFE_LEGACY_RENEGOTIATION_DISABLED when I try to create my initial authentication & refresh token. I have gone through all of the steps of the Authentication Workflow on the first page of this project and I simply cannot move on beyond the portion where my tokens are created. I have also tried this in two conda environments, one with 3.8 and the other with 3.10 with the same result. The output is shared below:
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1131)

**Comment by nittanycolonial** [comment]
I found this item that I believe is related to the issue above: https://github.com/openssl/openssl/issues/16278

**Comment by jerrychong25** [comment]
Same issue here but in Linux, waiting for solution

**Comment by nittanycolonial** [comment]
> Same issue here but in Linux, waiting for solution

I don't think this library is supported any more. I couldn't get beyond the above error - and I tried a lot of approaches - so I just gave up on this library and went to using the TDA API natively.

**Comment by jerrychong25** [comment]
> > Same issue here but in Linux, waiting for solution
> 
> I don't think this library is supported any more. I couldn't get beyond the above error - and I tried a lot of approaches - so I just gave up on this library and went to using the TDA API natively.

Oh I see, then I will look for other solution instead. Thank you very much @nittanycolonial !
