### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ramwins1** [areed1192/td-ameritrade-python-api#48]
**### PermissionError: [Errno 13] Permission denied?**

I dint use credentials path.

Traceback (most recent call last):
  File "c:/Personal/Trade/td-ameritrade-python-api-master/tests/unit/test_oauth.py", line 4, in <module>
    TDSession = TDClient(
  File "C:\Users\rp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\td\client.py", line 119, in __init__
    self._state_manager('init')
  File "C:\Users\rp\AppData\Local\Programs\Python\Python38-32\lib\site-packages\td\client.py", line 207, in _state_manager
    with open(file=credentials_file_path, mode='r') as json_file:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\rp\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\td'

**Comment by ramwins1** [comment]
solved: 
I have to add credentials_path , even though it was saying optional
