### ISSUE TITLE
async error

### ISSUE THREAD

**Issue by gsimanju** [areed1192/td-ameritrade-python-api#5]
I tried to run the test file and got this error.  I'm using phyton 3.8.

causes this error

C:\Users\Godwin\PycharmProjects\Autobot\venv\Scripts\python.exe C:/Users/Godwin/PycharmProjects/Autobot/test_td.client.py
Traceback (most recent call last):
  File "C:/Users/Godwin/PycharmProjects/Autobot/test_td.client.py", line 3, in <module>
    from td.client import TDClient
  File "C:\Users\Godwin\PycharmProjects\Autobot\venv\lib\site-packages\td\client.py", line 8, in <module>
    from td.stream import TDStreamerClient
  File "C:\Users\Godwin\PycharmProjects\Autobot\venv\lib\site-packages\td\stream.py", line 148
    await asyncio.sleep(1)
    ^
SyntaxError: 'await' outside async function

Process finished with exit code 1

**Comment by areed1192** [comment]
I changed it to an async function. Just an FYI the close_stream() function is still being modified, so I wouldn't use it just yet. I'll make an announcement when it's done.
