### ISSUE TITLE
calling cancel_order got a huge error

### ISSUE THREAD

**Issue by gsimanju** [areed1192/td-ameritrade-python-api#8]
So I run:
cancel_result = TDSession.cancel_order(account=ACCOUNT_NUMBER,
                                                                       order_id=positionRegister[key]['orderId'])

So the cancel order went through but then a huge error happens:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Godwin\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Godwin\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 804, in callit
    func(*args)
  File "C:/Users/Godwin/PycharmProjects/Autobot/autobot_v0_1_8.py", line 870, in updateLoop
    cancel_result = TDSession.cancel_order(account=ACCOUNT_NUMBER,
  File "C:\Users\Godwin\PycharmProjects\Autobot\venv\lib\site-packages\td_mod\client.py", line 1902, in cancel_order
    return requests.delete(url=url, headers=merged_headers,  verify=True).json()
  File "C:\Users\Godwin\PycharmProjects\Autobot\venv\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Godwin\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Godwin\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Godwin\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by gsimanju** [comment]
Found the problem.

cancel_order was sent as requests.delete().json() which is not correct. requests.delete doesn't get object back in json form, so I removed the .json() which solves the problem.
